Test: Add test/builds with input variations
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -46,3 +46,23 @@ jobs:
         with:
           path_prefix: "test-python-project/"
           purge_artefact_path: true
+
+      # Build with explicit versioning
+      - name: "Run action: ${{ github.repository }} [Explicit versioning]"
+        uses: ./
+        with:
+          path_prefix: "test-python-project/"
+          purge_artefact_path: true
+          tag: "v2.0.0"
+          artefact_path: "explicit_tag"
+          tox_build: false
+
+      - name: "Validate artefacts from above build"
+        shell: bash
+        run: |
+          # Validate artefacts from above build
+          if (find 'test-python-project/explicit_tag' -name '*2.0.0*'); then
+            echo "Explicit tag/artefact path as expected ✅"
+          else
+            echo "Error: build artefact validation failed ❌"; exit 1
+          fi
